### ISSUE TITLE
Error when specifying python.version

### ISSUE THREAD

**Issue by kyerpotts** [cachix/nixpkgs-python#16]
When attempting to specify a python version, I receive the following error:
error:
       … while updating the lock file of flake 'git+file:///home/squidmilk/Projects/VisualModule?ref=refs%2fheads%2fdev&rev=e2808402805fef9a1b890029794d72593d57eb05'

       … while updating the flake input 'nixpkgs-python'

       … while updating the flake input 'nixpkgs-python/flake-utils'

       error: cannot find flake 'flake:flake-utils' in the flake registrie

**Comment by kyerpotts** [comment]
I'm using devenv to create a python environment and trying to specify the python version. To do so I have to specify an input that points to nixpkgs-python.url = github:cachix/nixpkgs-python.
I then try to update devenv with the new inputs and nixpkgs-python gives an error stating that it can't find flake-utils

**Comment by domenkozar** [comment]
Can you please give the full example of files here, so that I can spot the error?

**Comment by kyerpotts** [comment]
devenv.yaml:
`inputs:
  nixpkgs:
    url: github:NixOS/nixpkgs/nixpkgs-unstable
  nixpkgs-python:
    url: github:cachix/nixpkgs-python
`
devenv.nix
{inputs, pkgs, ...}:
{
  packages = [pkgs.git ];
  languages.python.enable = true;
  languages.python.version = "3.9.2";
  languages.python.venv.enable = true;

  enterShell = ''
    git --version
  '';
}
