### ISSUE TITLE
Pip?

### ISSUE THREAD

**Issue by arogozhnikov** [cachix/nixpkgs-python#23]
Hi @domenkozar, thanks for the project.

I am currently trying to use python3.7 on mac os, and I miss how to install packages.

```
$ nix shell github:cachix/nixpkgs-python#'"3.7"' --extra-experimental-features nix-command --extra-experimental-features flakes
<installation>
$ python 3.7 -m pip
<says there is no pip>
```

Sorry if missing something obvious.

**Comment by domenkozar** [comment]
Interesting, I wonder why it's not building pip.

**Comment by ajaxbits** [comment]
Also having this issue

**Comment by jordan-bravo** [comment]
I'm having this issue with python `2.7`

**Comment by ktosiek** [comment]
A thing worth checking: run `python3.7 -m ensurepip`. This module is required to install pip in the venv.

**Comment by julianneswinoga** [comment]
Same problem with pip, with python 3.6:
```
$ python3.6 -m ensurepip
fish: Job 1, 'python3.6 -m ensurepip' terminated by signal SIGSEGV (Address boundary error)
```
Seems to be a problem with the build configuration: https://bugs.python.org/issue45700

**Comment by samvv** [comment]
I just installed 3.12.4. I can confirm that there still is no pip executable installed.

Also:

```
❯ python3.12 -m ensurepip
fish: Job 1, 'python3.12 -m ensurepip' terminated by signal SIGSEGV (Address boundary error)
```

**Comment by samvv** [comment]
My issue appears to be another issue. Opening a new one.
