### ISSUE TITLE
Update Python version action is failling

### ISSUE THREAD

**Issue by hensou** [cachix/nixpkgs-python#34]
Hi thank you for your work!

It seems that the update python action is stopped working some time  ago.

I went through the logs and it looks like it between on of these PR:

- https://github.com/cachix/nixpkgs-python/pull/24  
- https://github.com/cachix/nixpkgs-python/pull/25
- https://github.com/cachix/nixpkgs-python/pull/26
- https://github.com/cachix/nixpkgs-python/pull/26
- https://github.com/cachix/nixpkgs-python/pull/28

Is there anything I could do to help here?

**Comment by domenkozar** [comment]
It seems like we need to set a bound for `loongarch-support.patch`

**Comment by domenkozar** [comment]
let's see if a96f89da974e84c803ed1e652a4c3d207f294f59 fixes it

**Comment by domenkozar** [comment]
https://github.com/cachix/nixpkgs-python/actions/runs/8075580185
