### ISSUE TITLE
".interpreter" points to store location of Self interpreter

### ISSUE THREAD

**Issue by mauricege** [cachix/nixpkgs-python#4]
First of all, thanks for this great project!

Trying out the new python version option in devenv, I stumbled across the following error:

It seems like the ".interpreter" attribute evaluates to an invalid store path. The generated store path is constructed from `pkgs.self` which contains the interpreter for the "Self" programming language.

```console
› nix shell github:cachix/nixpkgs-python#'"3.11"'.interpreter
error: flake output attribute 'packages.x86_64-linux.3.11.interpreter' evaluates to the string '/nix/store/l6xbal1l3lfv21jkc6wirslc049yd068-self-2017.1/bin/python3.11' which is not a store path
```

The following line should be the one to blame, as `pkgs.callPackage` will set `self=pkgs.self` in `passthrufun.nix`:
https://github.com/cachix/nixpkgs-python/blob/a41ed95d94cc4bdf00174268d34985ce92dd41a5/flake.nix#L149

**Comment by domenkozar** [comment]
We have to pass self to the python file we're calling, but I'm not familiar with splicedPackages that much to understand how it all works.
