### ISSUE TITLE
python not working after fresh installation with devenv

### ISSUE THREAD

**Issue by PetitLepton** [cachix/nixpkgs-python#44]
Hi, 

I tried to install `python` several times on different linux machines using `devenv` with
```
  languages.python.enable = true;
  languages.python.version = "3.11";
```
Every installation leads to an error related to `libc`
```bash
/nix/store/jd2kphplkhxgajk6j3mp6j9s0w9awa9a-python3-3.11.9-env/bin/python: symbol lookup error: /nix/store/7v7c61ikm7cbd3kbimk9qr8h7pdmyccn-manylinux2014/lib/libc.so.6: undefined symbol: __tunable_is_initialized, version GLIBC_PRIVATE
```

I used `devenv` 1.0.3 and 1.0.7.

I found another [issue](https://github.com/NixOS/nixpkgs/issues/301798) showing the same problem in a different context.

I am new to `nix` and `devenv`. If you can pinpoint my mistake or a workaround, I would appreciate it. Thanks in advance!

**Comment by domenkozar** [comment]
Can you try setting `languages.python.manylinux.enable = false;`?

**Comment by PetitLepton** [comment]
@domenkozar It worked smoothly. Thank you!
