### ISSUE TITLE
cannot execute any python command, symbol lookup error under devenv shell 

### ISSUE THREAD

**Issue by fearofmusic443** [cachix/nixpkgs-python#46]
selected version 2.7.18. the `devenv shell` command appears to execute normally, however when I attempt to run python -v (or any other python command) I get the following error: 
`/nix/store/pvnkp62bk2c19nq2ssndyp7f3bya62yr-python-2.7.18-env/bin/python: symbol lookup error: /nix/store/7v7c61ikm7cbd3kbimk9qr8h7pdmyccn-manylinux2014/lib/libc.so.6: undefined symbol: __tunable_is_initialized, version GLIBC_PRIVATE`

heres my devenv.yaml and devenv.nix respectively:

`inputs:`
`  nixpkgs-python:`
`    url: github:cachix/nixpkgs-python`

### ---

`{ pkgs, ... }:`

`{`
`  languages.python.enable = true;`
`  languages.python.version = "2.7.18";`
`}`

**Comment by domenkozar** [comment]
`languages.python.manylinux.enable = false;`

**Comment by fearofmusic443** [comment]
> `languages.python.manylinux.enable = false;`

thank you, that appears to have done the trick.
