### ISSUE TITLE
Update action fails

### ISSUE THREAD

**Issue by ilkecan** [cachix/nixpkgs-python#57]
"Update" action fails for some time because the URL of at least one of the "ActiveState" versions that was previously saved returns 404:

https://github.com/cachix/nixpkgs-python/blob/7c550bca7e6cf95898e32eb2173efe7ebb447460/versions.json#L599-L602

https://github.com/cachix/nixpkgs-python/actions/runs/10814464898/job/30000992403#step:7:1127

I am not sure what is best course of action in this case:
1. Should the problematic versions simply be removed from `versions.json`? But that won't prevent the same thing happening again; considering "ActiveState" seem to deleted one of their releases, they might do the same thing again.
2. We could change "update.py" to handle previously saved but removed releases, at least for "ActiveState" versions.
3. Maybe the "ActiveState" versions should not be supported at all, if there will be an uncertainty for the existence of their releases.

**Comment by domenkozar** [comment]
For now it's best to just ignore that version in the script generating versions.json, but ideally we would parse some kind of index from them like we do for upstream releases.

**Comment by domenkozar** [comment]
fixed
